### ISSUE TITLE
brew 1.0.4 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [moshen/open-bash-completion#2]
relates to https://github.com/Homebrew/homebrew-core/pull/51502

```
$ brew test open-completion
Testing open-completion
==> source /usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open && complete -p open
/usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open: line 23: syntax error near unexpected token `<'
/usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open: line 23: `        while IFS=$'\n' read -r line; do COMPREPLY+=("$line"); done < <(IFS=$'\n' compgen -W "$applications" -- "$cur")'
Error: open-completion: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

somehow, it does work locally on my machine.

```
$ source /usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open && complete -p open
complete -o filenames -F _open open
```

Jenkins build ref, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/58965/version=catalina/console

**Comment by moshen** [comment]
I couldn't open the jenkins build (it might have expired), but an old bash version?

```
syntax error near unexpected token `<'
```

Makes me think that it doesn't like:

```
<(IFS=$'\n' compgen -W "$applications" -- "$cur")
```

**Comment by moshen** [comment]
I can't find exactly when the process substitution for files was introduced, but I have Catalina installed, which defaults to:

```
/bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

And it appears to work in that version of `bash`.  I can rewrite this bit to avoid using this feature if necessary.

**Comment by chenrui333** [comment]
@moshen yeah, it works on my local machine too, somehow does not work on the CI. 

Was thinking to open the issue to raise awareness, but guess the jenkins link is too old.

**Comment by moshen** [comment]
I figured it out.  It's running the test in `sh` and not `bash`:

```
sh-3.2$ source ./open
sh: ./open: line 23: syntax error near unexpected token `<'
sh: ./open: line 23: `        while IFS=$'\n' read -r line; do COMPREPLY+=("$line"); done < <(IFS=$'\n' compgen -W "$applications" -- "$cur")'
```

**Comment by moshen** [comment]
Closing this, as the fix is to update the test.

**Comment by chenrui333** [comment]
@moshen thanks, I will do that later and update in here. :)
